//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcsTranslateTool.Win.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DcsTranslateTool.Win.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   DCS Translate Tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認事項 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreatePullRequestDialogConfirmationLabel {
            get {
                return ResourceManager.GetString("CreatePullRequestDialogConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PRを作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreatePullRequestDialogCreatePRButtonContent {
            get {
                return ResourceManager.GetString("CreatePullRequestDialogCreatePRButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   主な変更点 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreatePullRequestDialogMainChangesLabel {
            get {
                return ResourceManager.GetString("CreatePullRequestDialogMainChangesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PRタイトル： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreatePullRequestDialogPRTitleLabel {
            get {
                return ResourceManager.GetString("CreatePullRequestDialogPRTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップロードするファイルリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreatePullRequestDialogUploadFileListHeader {
            get {
                return ResourceManager.GetString("CreatePullRequestDialogUploadFileListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   適用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageApplyButtonContent {
            get {
                return ResourceManager.GetString("DownloadPageApplyButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageDownloadButtonContent {
            get {
                return ResourceManager.GetString("DownloadPageDownloadButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取得 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageFetchButtonContent {
            get {
                return ResourceManager.GetString("DownloadPageFetchButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageFilterAllContent {
            get {
                return ResourceManager.GetString("DownloadPageFilterAllContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageFilterLocalOnlyText {
            get {
                return ResourceManager.GetString("DownloadPageFilterLocalOnlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更/更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageFilterModifiedText {
            get {
                return ResourceManager.GetString("DownloadPageFilterModifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未DL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageFilterRepoOnlyText {
            get {
                return ResourceManager.GetString("DownloadPageFilterRepoOnlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DL済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageFilterUnchangedText {
            get {
                return ResourceManager.GetString("DownloadPageFilterUnchangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダーを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageOpenDirectoryButtonContent {
            get {
                return ResourceManager.GetString("DownloadPageOpenDirectoryButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadPageTitle {
            get {
                return ResourceManager.GetString("DownloadPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定ページのプレースホルダーである。ここにアプリケーションの説明を記述する。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアプリケーションについて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーマ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダ設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageFolderSettingsTitle {
            get {
                return ResourceManager.GetString("SettingsPageFolderSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   個人用設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プライバシー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageResetButton {
            get {
                return ResourceManager.GetString("SettingsPageResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   参照... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageSelectButton {
            get {
                return ResourceManager.GetString("SettingsPageSelectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DCSのaircraftフォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageSourceAircraftDirText {
            get {
                return ResourceManager.GetString("SettingsPageSourceAircraftDirText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DCSのcampaignフォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageSourceDlcCampaignDirText {
            get {
                return ResourceManager.GetString("SettingsPageSourceDlcCampaignDirText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーフォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageSourceUserDirText {
            get {
                return ResourceManager.GetString("SettingsPageSourceUserDirText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロードフォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageTranslateFileDirText {
            get {
                return ResourceManager.GetString("SettingsPageTranslateFileDirText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PRを作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadPageCreatePRButtonContent {
            get {
                return ResourceManager.GetString("UploadPageCreatePRButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取得 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadPageFetchButtonContent {
            get {
                return ResourceManager.GetString("UploadPageFetchButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadPageFilterAllContent {
            get {
                return ResourceManager.GetString("UploadPageFilterAllContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadPageFilterLocalOnlyText {
            get {
                return ResourceManager.GetString("UploadPageFilterLocalOnlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更/更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadPageFilterModifiedText {
            get {
                return ResourceManager.GetString("UploadPageFilterModifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未DL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadPageFilterRepoOnlyText {
            get {
                return ResourceManager.GetString("UploadPageFilterRepoOnlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新無し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadPageFilterUnchangedText {
            get {
                return ResourceManager.GetString("UploadPageFilterUnchangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadPageTitle {
            get {
                return ResourceManager.GetString("UploadPageTitle", resourceCulture);
            }
        }
    }
}
