//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、予期しない動作の原因となる場合があります。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcsTranslateTool.Properties {
    using System;
    
    /// <summary>
    /// アプリ設定を表すクラス
    /// </summary>
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SettingsSingleFileGenerator", "1.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        /// <summary>
        /// 既定のインスタンスを取得する
        /// </summary>
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// SourceAircraftDir の設定値
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SourceAircraftDir {
            get {
                return ((string)(this["SourceAircraftDir"]));
            }
            set {
                this["SourceAircraftDir"] = value;
            }
        }
        
        /// <summary>
        /// SourceDlcCampaignDir の設定値
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SourceDlcCampaignDir {
            get {
                return ((string)(this["SourceDlcCampaignDir"]));
            }
            set {
                this["SourceDlcCampaignDir"] = value;
            }
        }
        
        /// <summary>
        /// SourceUserDir の設定値
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SourceUserDir {
            get {
                return ((string)(this["SourceUserDir"]));
            }
            set {
                this["SourceUserDir"] = value;
            }
        }
        
        /// <summary>
        /// TranslateFileDir の設定値
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TranslateFileDir {
            get {
                return ((string)(this["TranslateFileDir"]));
            }
            set {
                this["TranslateFileDir"] = value;
            }
        }
    }
}
