name: draft-release-on-release-branch

on:
  push:
    branches:
      - 'release/*'
      - 'hotfix/*'

permissions:
  contents: write

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.out.outputs.version }}
    steps:
      - id: out
        run: |
          # ref_name は "release/1.2.3" または "hotfix/1.2.3" 想定
          ver="$GITHUB_REF_NAME"
          if [[ "$ver" == release/* ]]; then
            ver="${ver#release/}"
          elif [[ "$ver" == hotfix/* ]]; then
            ver="${ver#hotfix/}"
          else
            # 想定外の分岐（保険）: 最後の要素を採用
            ver="${ver##*/}"
          fi
          echo "version=$ver" >> "$GITHUB_OUTPUT"

  draft:
    needs: prep
    uses: ./.github/workflows/release-common.yml
    with:
      mode: draft
      cancel_in_progress: true
      fail_fast: true
      rid_list: '["win-x64","win-x86"]'
      dotnet_version: '8.0.x'
      version_name: ${{ needs.prep.outputs.version }}
    secrets:
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
