name: publish-release-on-tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.out.outputs.version }}
    steps:
      - id: out
        run: |
          # ref_name は "v1.2.3"
          ver="${GITHUB_REF_NAME#v}"   # 先頭の v を除去
          echo "version=$ver" >> "$GITHUB_OUTPUT"

  publish:
    needs: prep
    uses: ./.github/workflows/release-common.yml
    with:
      mode: publish
      cancel_in_progress: false
      fail_fast: false
      rid_list: '["win-x64","win-x86"]'
      dotnet_version: '8.0.x'
      version_name: ${{ needs.prep.outputs.version }}
    secrets:
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
