name: Run Unit Tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore DcsTranslateTool.sln
      - name: Build
        run: dotnet build DcsTranslateTool.sln --no-restore
      - name: Test
        run: dotnet test DcsTranslateTool.sln --no-build --verbosity normal
